#!/usr/bin/env node
/**
 * build-docx.js — JSON-spec docx builder for /analyze-video.
 *
 * Reads a JSON spec describing the document structure (title, per-video
 * sections, frame paths, captions) and writes a polished .docx. This
 * replaces the old "edit a template, then run" workflow with a single
 * `node build-docx.js --spec spec.json` call, so the skill never has
 * to write JavaScript at runtime.
 *
 * Spec shape (all fields optional unless marked required):
 * {
 *   "out": "/abs/path/output.docx",                  // REQUIRED
 *   "title": "Video Analysis",                       // REQUIRED
 *   "subtitle": "Generated by /analyze-video",
 *   "image_dimensions": { "width": 480, "height": 270 },
 *   "videos": [                                      // REQUIRED, 1+
 *     {
 *       "title": "Video Title",
 *       "meta": "Uploader · Duration · Source URL",
 *       "image_dimensions": { "width": 480, "height": 360 },  // overrides global
 *       "sections": [
 *         {
 *           "heading": "Opening (0:00–0:15)",
 *           "body": "Paragraph of analysis prose...",
 *           "frames": [
 *             {
 *               "path": "/abs/path/frame_0001.jpg",  // REQUIRED
 *               "caption": "Caption text.",
 *               "width": 480,                         // optional override
 *               "height": 270
 *             }
 *           ]
 *         }
 *       ]
 *     }
 *   ],
 *   "observations": "Cross-video observations..."    // optional, batch only
 * }
 *
 * Usage:
 *   node build-docx.js --spec /path/to/spec.json
 *   cat spec.json | node build-docx.js --spec -
 */

const { Document, Packer, Paragraph, TextRun, ImageRun } = require('docx');
const fs = require('fs');
const path = require('path');

// ----------------------------------------------------------------------------
// Paragraph helpers
// ----------------------------------------------------------------------------

function title(text) {
  return new Paragraph({
    spacing: { before: 0, after: 120 },
    children: [new TextRun({ text, bold: true, size: 44, font: 'Arial', color: '0D0D0D' })],
  });
}

function meta(text) {
  return new Paragraph({
    spacing: { before: 0, after: 260 },
    children: [new TextRun({ text, italics: true, size: 20, color: '888888', font: 'Arial' })],
  });
}

function h1(text) {
  return new Paragraph({
    spacing: { before: 440, after: 180 },
    children: [new TextRun({ text, bold: true, size: 36, font: 'Arial', color: '1A1A1A' })],
  });
}

function h2(text) {
  return new Paragraph({
    spacing: { before: 300, after: 120 },
    children: [new TextRun({ text, bold: true, size: 24, font: 'Arial', color: '2D6A9F' })],
  });
}

function body(text) {
  // Split on blank lines so multi-paragraph body text renders correctly
  // (TextRun does not honor \n; each paragraph is its own element).
  const blocks = String(text || '').split(/\n\s*\n/).map(s => s.trim()).filter(Boolean);
  if (blocks.length === 0) return [];
  return blocks.map(block => new Paragraph({
    spacing: { before: 0, after: 180 },
    children: [new TextRun({ text: block, size: 22, font: 'Arial' })],
  }));
}

function imgPara(filePath, dim, alt) {
  const transformation = {
    width: (dim && dim.width) || 480,
    height: (dim && dim.height) || 270,
  };
  return new Paragraph({
    spacing: { before: 220, after: 0 },
    children: [new ImageRun({
      type: 'jpg',                                       // REQUIRED for jpg
      data: fs.readFileSync(filePath),
      transformation,
      altText: {                                          // all 3 fields REQUIRED
        title: 'frame',
        description: alt || 'video frame',
        name: 'frame',
      },
    })],
  });
}

function cap(text) {
  return new Paragraph({
    spacing: { before: 60, after: 280 },
    children: [new TextRun({ text, italics: true, size: 18, color: '777777', font: 'Arial' })],
  });
}

// ----------------------------------------------------------------------------
// Spec -> children
// ----------------------------------------------------------------------------

function buildChildren(spec) {
  if (!spec || typeof spec !== 'object') {
    throw new Error('spec must be an object');
  }
  if (!spec.title) throw new Error('spec.title is required');
  if (!Array.isArray(spec.videos) || spec.videos.length === 0) {
    throw new Error('spec.videos must be a non-empty array');
  }

  const globalDim = spec.image_dimensions || { width: 480, height: 270 };
  const children = [title(spec.title)];
  if (spec.subtitle) children.push(meta(spec.subtitle));

  for (const video of spec.videos) {
    if (!video || typeof video !== 'object') continue;
    if (video.title) children.push(h1(video.title));
    if (video.meta) children.push(meta(video.meta));
    const videoDim = video.image_dimensions || globalDim;

    const sections = Array.isArray(video.sections) ? video.sections : [];
    for (const section of sections) {
      if (!section || typeof section !== 'object') continue;
      if (section.heading) children.push(h2(section.heading));
      if (section.body) children.push(...body(section.body));

      const frames = Array.isArray(section.frames) ? section.frames : [];
      for (const frame of frames) {
        if (!frame || !frame.path) continue;
        const dim = (frame.width && frame.height)
          ? { width: frame.width, height: frame.height }
          : videoDim;
        children.push(imgPara(frame.path, dim, frame.caption || 'video frame'));
        if (frame.caption) children.push(cap(frame.caption));
      }
    }
  }

  if (spec.observations) {
    children.push(h1('Observations Across Videos'));
    children.push(...body(spec.observations));
  }
  return children;
}

async function buildDoc(spec) {
  const children = buildChildren(spec);
  const doc = new Document({
    sections: [{
      properties: {
        page: {
          size: { width: 12240, height: 15840 },        // US Letter
          margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 },
        },
      },
      children,
    }],
  });
  return Packer.toBuffer(doc);
}

// ----------------------------------------------------------------------------
// CLI
// ----------------------------------------------------------------------------

function readSpec(specArg) {
  if (specArg === '-' || specArg === '/dev/stdin') {
    // fs.readFileSync on fd 0 reads stdin to EOF in one shot.
    return JSON.parse(fs.readFileSync(0, 'utf-8'));
  }
  return JSON.parse(fs.readFileSync(specArg, 'utf-8'));
}

if (require.main === module) {
  const args = process.argv.slice(2);
  const specIdx = args.indexOf('--spec');
  if (specIdx === -1 || !args[specIdx + 1]) {
    console.error('usage: build-docx.js --spec <path-to-spec.json|->');
    console.error('');
    console.error('Spec must include: out, title, videos[].');
    console.error('See header comment in this file for the full schema.');
    process.exit(2);
  }
  const spec = readSpec(args[specIdx + 1]);
  if (!spec.out) {
    console.error('error: spec.out is required (absolute path for the .docx)');
    process.exit(2);
  }
  buildDoc(spec).then(buf => {
    fs.mkdirSync(path.dirname(spec.out), { recursive: true });
    fs.writeFileSync(spec.out, buf);
    console.log('wrote ' + spec.out);
  }).catch(err => {
    console.error(err.stack || err.message || String(err));
    process.exit(1);
  });
}

module.exports = { buildChildren, buildDoc };
