#!/usr/bin/env node
/**
 * build-docx.js — JSON-spec docx builder for /analyze-video.
 *
 * Reads a JSON spec describing the document structure (title, per-video
 * sections, frame paths, captions) and writes a polished .docx. This
 * replaces the old "edit a template, then run" workflow with a single
 * `node build-docx.js --spec spec.json` call, so the skill never has
 * to write JavaScript at runtime.
 *
 * Spec shape (all fields optional unless marked required):
 * {
 *   "out": "/abs/path/output.docx",                  // REQUIRED
 *   "title": "Video Analysis",                       // REQUIRED
 *   "subtitle": "Generated by /analyze-video",
 *   "image_dimensions": { "width": 480, "height": 270 },
 *   "videos": [                                      // REQUIRED, 1+
 *     {
 *       "title": "Video Title",
 *       "source": "https://youtu.be/... or /local/path.mp4",  // shown under title
 *       "meta": "Uploader · Duration · Source URL",
 *       "image_dimensions": { "width": 480, "height": 360 },  // overrides global
 *       "sections": [
 *         {
 *           "heading": "Opening (0:00–0:15)",
 *           "body": "Paragraph of analysis prose...",
 *           "frames": [
 *             {
 *               "path": "/abs/path/frame_0001.jpg",  // REQUIRED
 *               "caption": "Caption text.",
 *               "width": 480,                         // optional override
 *               "height": 270
 *             }
 *           ]
 *         }
 *       ]
 *     }
 *   ],
 *   "observations": "Cross-video observations..."    // optional, batch only
 *   "appendix_contact_sheets": [                      // optional appendix
 *     {
 *       "path": "/abs/path/contact_sheet.jpg",        // REQUIRED
 *       "heading": "Title — chunk 2 (10:00–20:00)",   // optional H2
 *       "caption": "Frames 0:00–10:00",               // optional, also used as alt
 *       "alt": "Accessible description of the grid",   // optional alt override
 *       "width": 600, "height": 800                    // optional; auto from JPEG if omitted
 *     }
 *   ],
 *   "appendix_transcript": [                           // optional appendix
 *     {
 *       "heading": "Video Title",                       // optional H2
 *       "path": "/abs/path/transcript.txt"              // preferred: builder reads the file
 *       // or inline: "lines": ["[0:00] ...", ...]  or  "text": "[0:00] ...\n..."
 *     }
 *   ]
 * }
 *
 * Usage:
 *   node build-docx.js --spec /path/to/spec.json
 *   cat spec.json | node build-docx.js --spec -
 */

const fs = require('fs');
const path = require('path');
const os = require('os');

// ----------------------------------------------------------------------------
// docx module resolution
// ----------------------------------------------------------------------------
// The skill directory (where this script lives) may be mounted read-only, so we
// can't rely on a `scripts/node_modules/docx` being present or installable here.
// Resolve `docx` from any writable/known location, and only as a last resort
// install it into a per-user cache. This avoids the silent EACCES failures that
// happen when `npm install` targets a read-only skill directory.
function resolveDocx() {
  const cacheModules = path.join(os.homedir(), '.cache', 'analyze-video', 'node_modules');
  const roots = [];
  if (process.env.DOCX_NODE_MODULES) roots.push(process.env.DOCX_NODE_MODULES);
  if (process.env.NODE_PATH) roots.push(...process.env.NODE_PATH.split(path.delimiter).filter(Boolean));
  roots.push(path.join(__dirname, 'node_modules'));
  roots.push(cacheModules);

  for (const root of roots) {
    try {
      return require(path.join(root, 'docx'));
    } catch (e) { /* try next root */ }
  }
  // Default Node resolution (covers a docx installed anywhere up the tree).
  try {
    return require('docx');
  } catch (e) { /* fall through to install */ }

  // Last resort: install into the writable per-user cache, then load it.
  const cacheParent = path.dirname(cacheModules); // ~/.cache/analyze-video
  try {
    fs.mkdirSync(cacheParent, { recursive: true });
    const { execFileSync } = require('child_process');
    process.stderr.write('[build-docx] installing docx into ' + cacheModules + ' ...\n');
    execFileSync('npm', ['install', 'docx@^9', '--no-audit', '--no-fund', '--prefix', cacheParent], {
      stdio: ['ignore', 'ignore', 'inherit'],
    });
    return require(path.join(cacheModules, 'docx'));
  } catch (e) {
    process.stderr.write(
      '[build-docx] ERROR: could not load or install the `docx` module.\n' +
      '  Tried: ' + roots.join(', ') + '\n' +
      '  The skill directory may be read-only. Fixes:\n' +
      '   - set NODE_PATH to a directory containing docx, or\n' +
      '   - run `python3 scripts/setup.py --install-docx` once in a writable checkout, or\n' +
      '   - allow this script to install docx into ' + cacheModules + '.\n' +
      '  Underlying error: ' + e.message + '\n'
    );
    process.exit(1);
  }
}

const {
  Document, Packer, Paragraph, TextRun, ImageRun,
  Table, TableRow, TableCell, WidthType, BorderStyle, TableBorders,
} = resolveDocx();

// ----------------------------------------------------------------------------
// Paragraph helpers
// ----------------------------------------------------------------------------

function title(text) {
  return new Paragraph({
    spacing: { before: 0, after: 120 },
    children: [new TextRun({ text, bold: true, size: 44, font: 'Arial', color: '0D0D0D' })],
  });
}

function meta(text) {
  return new Paragraph({
    spacing: { before: 0, after: 260 },
    children: [new TextRun({ text, italics: true, size: 20, color: '888888', font: 'Arial' })],
  });
}

// Readable "Source: <url-or-path>" line under a video title. Kept at normal body
// contrast (not the faint meta grey) so the provenance of the analyzed video is
// legible and screen-reader friendly.
function sourceLine(text) {
  return new Paragraph({
    spacing: { before: 0, after: 200 },
    children: [
      new TextRun({ text: 'Source: ', bold: true, size: 20, color: '333333', font: 'Arial' }),
      new TextRun({ text: String(text), size: 20, color: '333333', font: 'Arial' }),
    ],
  });
}

// One transcript line (already formatted, typically "[12:34] spoken text").
// Body-sized for readability; plain text so screen readers handle it cleanly.
function transcriptLine(text) {
  return new Paragraph({
    spacing: { before: 0, after: 40 },
    children: [new TextRun({ text: String(text), size: 20, font: 'Arial' })],
  });
}

function h1(text) {
  return new Paragraph({
    spacing: { before: 440, after: 180 },
    children: [new TextRun({ text, bold: true, size: 36, font: 'Arial', color: '1A1A1A' })],
  });
}

function h2(text) {
  return new Paragraph({
    spacing: { before: 300, after: 120 },
    children: [new TextRun({ text, bold: true, size: 24, font: 'Arial', color: '2D6A9F' })],
  });
}

function body(text) {
  // Split on blank lines so multi-paragraph body text renders correctly
  // (TextRun does not honor \n; each paragraph is its own element).
  const blocks = String(text || '').split(/\n\s*\n/).map(s => s.trim()).filter(Boolean);
  if (blocks.length === 0) return [];
  return blocks.map(block => new Paragraph({
    spacing: { before: 0, after: 180 },
    children: [new TextRun({ text: block, size: 22, font: 'Arial' })],
  }));
}

function imgPara(filePath, dim, alt) {
  const w = (dim && typeof dim.width === 'number' && dim.width > 0) ? dim.width : 480;
  const h = (dim && typeof dim.height === 'number' && dim.height > 0) ? dim.height : 270;
  const transformation = { width: w, height: h };
  if (!fs.existsSync(filePath)) {
    // Skip missing frames gracefully — return a placeholder caption
    return new Paragraph({
      spacing: { before: 220, after: 0 },
      children: [new TextRun({
        text: `[missing frame: ${filePath}]`,
        italics: true, size: 18, color: 'CC0000', font: 'Arial',
      })],
    });
  }
  return new Paragraph({
    spacing: { before: 220, after: 0 },
    children: [new ImageRun({
      type: 'jpg',                                       // REQUIRED for jpg
      data: fs.readFileSync(filePath),
      transformation,
      altText: {                                          // all 3 fields REQUIRED
        title: 'frame',
        description: alt || 'video frame',
        name: 'frame',
      },
    })],
  });
}

function cap(text) {
  return new Paragraph({
    spacing: { before: 60, after: 280 },
    children: [new TextRun({ text, italics: true, size: 18, color: '777777', font: 'Arial' })],
  });
}

// ----------------------------------------------------------------------------
// 2-up frame layout (side-by-side pairs in a borderless table)
// ----------------------------------------------------------------------------
// Max width per cell so two frames fit across the ~6.5in content column. ~300px
// at 96dpi ≈ 3.1in, leaving room for cell margins.
const TWO_UP_MAX_W = 300;

function scaledForTwoUp(dim) {
  const w0 = (dim && typeof dim.width === 'number' && dim.width > 0) ? dim.width : 480;
  const h0 = (dim && typeof dim.height === 'number' && dim.height > 0) ? dim.height : 270;
  // Clamp width to the cell; preserve aspect ratio. Honors per-frame overrides
  // (which feed in via dim) without letting them overflow the column.
  const scale = Math.min(1, TWO_UP_MAX_W / w0);
  return { width: Math.max(1, Math.round(w0 * scale)), height: Math.max(1, Math.round(h0 * scale)) };
}

function noCellBorders() {
  const none = { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' };
  return { top: none, bottom: none, left: none, right: none };
}

function frameCell(frame, videoDim) {
  if (!frame || !frame.path) {
    // Filler cell to balance an odd final pair (keeps the table rectangular).
    return new TableCell({
      children: [new Paragraph({})],
      width: { size: 50, type: WidthType.PERCENTAGE },
      borders: noCellBorders(),
    });
  }
  const baseDim = (frame.width && frame.height)
    ? { width: frame.width, height: frame.height }
    : videoDim;
  const children = [imgPara(frame.path, scaledForTwoUp(baseDim), frame.caption || 'video frame')];
  if (frame.caption) children.push(cap(frame.caption));
  return new TableCell({
    children,
    width: { size: 50, type: WidthType.PERCENTAGE },
    borders: noCellBorders(),
    margins: { top: 40, bottom: 120, left: 40, right: 40 },
  });
}

// Render frames two-per-row in a borderless table. Returns an array with a
// single Table element (or empty if there are no frames).
function framesTwoUp(frames, videoDim) {
  const valid = frames.filter(f => f && f.path);
  if (valid.length === 0) return [];
  const rows = [];
  for (let i = 0; i < valid.length; i += 2) {
    rows.push(new TableRow({
      children: [frameCell(valid[i], videoDim), frameCell(valid[i + 1], videoDim)],
    }));
  }
  return [new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    borders: TableBorders.NONE,
    rows,
  })];
}

// Read intrinsic JPEG dimensions from SOF markers so contact-sheet grids keep
// their aspect ratio (no explicit width/height needed from the caller).
function jpegSize(buf) {
  if (!buf || buf.length < 4 || buf[0] !== 0xff || buf[1] !== 0xd8) return null;
  let off = 2;
  while (off + 9 < buf.length) {
    if (buf[off] !== 0xff) { off += 1; continue; }
    const marker = buf[off + 1];
    // SOF0..SOF15 (skip DHT/DAC/RSTn which aren't frame headers): C0-CF except C4,C8,CC
    if (marker >= 0xc0 && marker <= 0xcf && marker !== 0xc4 && marker !== 0xc8 && marker !== 0xcc) {
      const height = buf.readUInt16BE(off + 5);
      const width = buf.readUInt16BE(off + 7);
      return { width, height };
    }
    const segLen = buf.readUInt16BE(off + 2);
    if (segLen < 2) return null;
    off += 2 + segLen;
  }
  return null;
}

// Render a contact sheet scaled to fit the page while preserving aspect ratio.
function contactSheetPara(filePath, alt, explicitDim) {
  const MAX_W = 600;
  const MAX_H = 860;
  if (!fs.existsSync(filePath)) {
    return new Paragraph({
      spacing: { before: 220, after: 0 },
      children: [new TextRun({
        text: `[missing contact sheet: ${filePath}]`,
        italics: true, size: 18, color: 'CC0000', font: 'Arial',
      })],
    });
  }
  const data = fs.readFileSync(filePath);
  let w = MAX_W;
  let h = Math.round(MAX_W * 0.66);
  const intrinsic = (explicitDim && explicitDim.width && explicitDim.height)
    ? { width: explicitDim.width, height: explicitDim.height }
    : jpegSize(data);
  if (intrinsic && intrinsic.width > 0 && intrinsic.height > 0) {
    const scale = Math.min(MAX_W / intrinsic.width, MAX_H / intrinsic.height, 1);
    w = Math.max(1, Math.round(intrinsic.width * scale));
    h = Math.max(1, Math.round(intrinsic.height * scale));
  }
  return new Paragraph({
    spacing: { before: 220, after: 0 },
    children: [new ImageRun({
      type: 'jpg',
      data,
      transformation: { width: w, height: h },
      altText: {
        title: 'contact sheet',
        description: alt || 'contact sheet: grid of video frames',
        name: 'contact sheet',
      },
    })],
  });
}

// ----------------------------------------------------------------------------
// Spec -> children
// ----------------------------------------------------------------------------

// Resolve the text lines for one transcript-appendix entry. Prefers reading a
// local transcript file by `path` (robust for long videos: the builder reads the
// file directly instead of the caller re-emitting huge text into the spec).
// Falls back to an inline `lines` array or a `text` string for small snippets.
function transcriptLinesFor(entry) {
  if (entry && entry.path) {
    try {
      const raw = fs.readFileSync(entry.path, 'utf-8');
      return raw.split(/\r?\n/).map((l) => l.replace(/\s+$/, '')).filter((l) => l.length > 0);
    } catch (err) {
      return [`[missing transcript file: ${entry.path}]`];
    }
  }
  if (Array.isArray(entry && entry.lines)) {
    return entry.lines.map((l) => String(l)).filter((l) => l.trim().length > 0);
  }
  if (entry && typeof entry.text === 'string') {
    return entry.text.split(/\r?\n/).map((l) => l.replace(/\s+$/, '')).filter((l) => l.length > 0);
  }
  return [];
}

function buildChildren(spec) {
  if (!spec || typeof spec !== 'object') {
    throw new Error('spec must be an object');
  }
  if (!spec.title) throw new Error('spec.title is required');
  if (!Array.isArray(spec.videos) || spec.videos.length === 0) {
    throw new Error('spec.videos must be a non-empty array');
  }

  const globalDim = spec.image_dimensions || { width: 480, height: 270 };
  // Frame layout: "1up" (default, one frame per row) or "2up" (side-by-side
  // pairs). Set at the spec level and overridable per video or per section.
  const globalLayout = spec.frame_layout === '2up' ? '2up' : '1up';
  const children = [title(spec.title)];
  if (spec.subtitle) children.push(meta(spec.subtitle));

  for (const video of spec.videos) {
    if (!video || typeof video !== 'object') continue;
    if (video.title) children.push(h1(video.title));
    if (video.source) children.push(sourceLine(video.source));
    if (video.meta) children.push(meta(video.meta));
    const videoDim = video.image_dimensions || globalDim;
    const videoLayout = video.frame_layout
      ? (video.frame_layout === '2up' ? '2up' : '1up')
      : globalLayout;

    const sections = Array.isArray(video.sections) ? video.sections : [];
    for (const section of sections) {
      if (!section || typeof section !== 'object') continue;
      if (section.heading) children.push(h2(section.heading));
      if (section.body) children.push(...body(section.body));

      const frames = Array.isArray(section.frames) ? section.frames : [];
      const layout = section.frame_layout
        ? (section.frame_layout === '2up' ? '2up' : '1up')
        : videoLayout;

      if (layout === '2up') {
        children.push(...framesTwoUp(frames, videoDim));
        continue;
      }
      for (const frame of frames) {
        if (!frame || !frame.path) continue;
        const dim = (frame.width && frame.height)
          ? { width: frame.width, height: frame.height }
          : videoDim;
        children.push(imgPara(frame.path, dim, frame.caption || 'video frame'));
        if (frame.caption) children.push(cap(frame.caption));
      }
    }
  }

  if (spec.observations) {
    children.push(h1('Observations Across Videos'));
    children.push(...body(spec.observations));
  }

  // Optional appendix: tiled contact-sheet overviews (one per chunk/video).
  // Off unless the spec includes them; each entry keeps its aspect ratio and
  // carries required alt text for accessibility.
  const sheets = Array.isArray(spec.appendix_contact_sheets) ? spec.appendix_contact_sheets : [];
  const validSheets = sheets.filter((s) => s && s.path);
  if (validSheets.length > 0) {
    children.push(h1('Contact Sheet Appendix'));
    children.push(...body(
      'Each grid below is a chronological overview of the extracted frames for a '
      + 'video (or chunk). Use it as a visual index of the full timeline.'
    ));
    for (const sheet of validSheets) {
      if (sheet.heading) children.push(h2(sheet.heading));
      const dim = (sheet.width && sheet.height)
        ? { width: sheet.width, height: sheet.height }
        : null;
      const alt = sheet.alt || sheet.caption || 'contact sheet: grid of video frames';
      children.push(contactSheetPara(sheet.path, alt, dim));
      if (sheet.caption) children.push(cap(sheet.caption));
    }
  }

  // Optional appendix: full transcript text. Off unless the spec includes it.
  // Each entry should carry a `path` to a transcript file (preferred) or inline
  // `lines`/`text`; entries with no resolvable content are skipped.
  const transcripts = Array.isArray(spec.appendix_transcript) ? spec.appendix_transcript : [];
  const resolvedTranscripts = transcripts
    .map((entry) => ({ entry, lines: transcriptLinesFor(entry) }))
    .filter((t) => t.lines.length > 0);
  if (resolvedTranscripts.length > 0) {
    children.push(h1('Transcript Appendix'));
    children.push(...body(
      'The full transcript of each video (or chunk) is reproduced below for '
      + 'reference. Timestamps mark when each line is spoken.'
    ));
    for (const { entry, lines } of resolvedTranscripts) {
      if (entry.heading) children.push(h2(entry.heading));
      for (const line of lines) children.push(transcriptLine(line));
    }
  }
  return children;
}

async function buildDoc(spec) {
  const children = buildChildren(spec);
  const doc = new Document({
    sections: [{
      properties: {
        page: {
          size: { width: 12240, height: 15840 },        // US Letter
          margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 },
        },
      },
      children,
    }],
  });
  return Packer.toBuffer(doc);
}

// ----------------------------------------------------------------------------
// CLI
// ----------------------------------------------------------------------------

function readSpec(specArg) {
  if (specArg === '-' || specArg === '/dev/stdin') {
    // fs.readFileSync on fd 0 reads stdin to EOF in one shot.
    return JSON.parse(fs.readFileSync(0, 'utf-8'));
  }
  return JSON.parse(fs.readFileSync(specArg, 'utf-8'));
}

if (require.main === module) {
  const args = process.argv.slice(2);
  const specIdx = args.indexOf('--spec');
  if (specIdx === -1 || !args[specIdx + 1]) {
    console.error('usage: build-docx.js --spec <path-to-spec.json|->');
    console.error('');
    console.error('Spec must include: out, title, videos[].');
    console.error('See header comment in this file for the full schema.');
    process.exit(2);
  }
  const spec = readSpec(args[specIdx + 1]);
  if (!spec.out) {
    console.error('error: spec.out is required (absolute path for the .docx)');
    process.exit(2);
  }
  buildDoc(spec).then(buf => {
    fs.mkdirSync(path.dirname(spec.out), { recursive: true });
    fs.writeFileSync(spec.out, buf);
    console.log('wrote ' + spec.out);
  }).catch(err => {
    console.error(err.stack || err.message || String(err));
    process.exit(1);
  });
}

module.exports = { buildChildren, buildDoc };
